<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\User;


return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        $user = User::where('is_admin', 1)->first();
        if ($user) {
            $user->update(['permissions' => $this->adminPermissions()]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down()
    {
        $user = User::where('is_super_admin', 1)->first();
        if ($user) {
            $user->update(['permissions' => $this->superAdminPermissions()]);
        }
    }


    public function superAdminPermissions()
    {
        return [
            'user_create',
            'user_read',
            'user_update',
            'user_delete',
            'user_account_activity_read',
            'user_payment_logs_read',
            'user_logout_from_devices',

            'role_create',
            'role_read',
            'role_update',
            'role_delete',
            'sms_setting_update',

            'apikeys.index',
            'apikeys.create',
            'apikeys.edit',
            'apikeys.revoke',
            'apikeys.destroy',
            're_captcha_setting',

            'hero.index',
            'hero.create',
            'hero.edit',
            'hero.destroy',

            'permission_read',
            'permission_create',
            'permission_update',
            'permission_delete',

            'manage_plan',
            'manage_domain',
            'usage',
            'sms.history',
            'sms.credit',
            'utility',
            'plan_limitation',
            'mobile_app',

            'merchant_create',
            'merchant_read',
            'use_all_merchant',
            'read_all_merchant',
            'merchant_update',
            'merchant_delete',
            'merchant_shop_read',
            'merchant_shop_create',
            'merchant_shop_delete',
            'merchant_shop_update',
            'merchant_payment_account_read',
            'merchant_payment_account_update',
            'merchant_account_activity_read',
            'merchant_cod_charge_read',
            'merchant_charge_read',
            'merchant_payment_logs_read',
            'merchant_api_credentials_read',
            'merchant_api_credentials_update',
            'merchant_staff_read',
            'merchant_staff_create',
            'merchant_staff_update',
            'download_closing_report',

            'deliveryman_create',
            'deliveryman_read',
            'read_all_delivery_man',
            'use_all_delivery_man',
            'deliveryman_update',
            'deliveryman_delete',
            'deliveryman_account_activity_read',
            'deliveryman_payment_logs_read',

            'parcel_create',
            'parcel_read',
            'parcel_update',
            'parcel_delete',

            'read_all_parcel',
            'parcel_pickup_assigned',
            'parcel_reschedule_pickup',
            'parcel_received_by_pickup_man',
            'parcel_received',
            'parcel_transfer_to_branch',
            'parcel_transfer_receive_to_branch',
            'parcel_delivery_assigned',
            'parcel_reschedule_delivery',
            'parcel_returned_to_warehouse',
            'parcel_return_assigned_to_merchant',
            'parcel_delivered',
            'parcel_backward',
            'parcel_returned_to_merchant',
            'parcel_cancel',
            'parcel_delete',
            'send_to_paperfly',

            'income_create',
            'income_read',
            'read_all_income',
            'income_update',
            'income_delete',

            'expense_create',
            'expense_read',
            'read_all_expense',
            'expense_update',
            'expense_delete',

            'withdraw_read',
            'read_all_withdraw',
            'withdraw_create',
            'withdraw_update',
            'withdraw_process',
            'withdraw_reject',
            'add_to_bulk_withdraw',

            'sms_setting_read',
            'sms_setting_update',
            'sms_campaign_message_send',
            'custom_sms_send',

            'report_read',
            'transaction_history_read',
            'parcels_summary_read',
            'total_summary_read',
            'income_expense_report_read',
            'profit_summary_report_read',
            'merchant_summary_report_read',
            'dashboard_statistics_read',

            'account_read',
            'account_create',
            'account_update',
            'read_all_account',
            'account_statement',

            'fund_transfer_read',
            'read_all_fund_transfer',
            'fund_transfer_create',
            'fund_transfer_update',
            'fund_transfer_delete',

            'branch_read',
            'branch_create',
            'branch_update',
            'branch_delete',

            'email_template_read',
            'email_template_create',
            'email_template_update',
            'email_template_delete',
            'email_configuration',

            'third_party_read',
            'third_party_create',
            'third_party_update',
            'third_party_delete',

            'language_read',
            'language_create',
            'language_update',
            'language_delete',

            'payment_method_read',
            'payment_method_create',
            'payment_method_update',
            'payment_method_delete',

            'country_read',
            'country_create',
            'country_update',
            'country_delete',

            "email_template_read",
            "email_template_create",
            "email_template_update",
            "email_template_delete",

            'notice_read',
            'notice_create',
            'notice_update',
            'notice_delete',
            'extension_library',
            'filesystem',

            'settings_read',
            'sms_settings_update',
            'charge_setting_update',
            'pickup_and_delivery_time_setting_update',
            'preference_setting_update',
            'panel_setting',
            'preference',
            'payment_method',
            'general_setting',
            'pickup_and_delivery_time_setting_update',
            'charge_setting',
            'packaging_charge_setting',
            'preference_setting',

            'storage_setting',
            'pusher_setting',
            'cron_setting',
            'sms_gateway',
            'server_info',
            'system_update',

            'bulk_withdraw_read',
            'read_all_bulk_withdraw',
            'bulk_withdraw_create',
            'bulk_withdraw_update',
            'bulk_withdraw_process',
            'download_payment_sheet',

            'news_and_event.index',
            'news_and_event.create',
            'news_and_event.edit',
            'news_and_event.destroy',
            'about.index',
            'about.create',
            'about.edit',
            'about.destroy',
            'service.index',
            'service.create',
            'service.edit',
            'service.destroy',
            'feature.index',
            'feature.create',
            'feature.edit',
            'feature.destroy',
            'statistic.index',
            'statistic.create',
            'statistic.edit',
            'statistic.destroy',
            'price.section',
            'contact.section',
            'website.themes',
            'website.menu',
            'section.title',
            'website.cta',
            'footer.content',
            'website_setting.seo',
            'website_setting.custom_js',
            'website_setting.custom_css',
            'website_setting.google_setup',
            'website_setting.fb_pixel',
            'partner_logo.index',
            'partner_logo.create',
            'partner_logo.edit',
            'partner_logo.destroy',
            'testimonial.index',
            'testimonial.create',
            'testimonial.edit',
            'testimonial.destroy',
            'faq.index',
            'faq.create',
            'faq.destroy',
            'faq.edit',
            'pages.index',
            'pages.create',
            'pages.edit',
            'pages.destroy',
        ];
    }
    public function adminPermissions()
    {
        return [
            'user_create',
            'user_read',
            'user_update',
            'user_account_activity_read',
            'user_payment_logs_read',
            'user_logout_from_devices',
            'sms_setting_update',
            'sms.history',

            'role_create',
            'role_read',
            'role_update',

            'hero.index',
            'hero.create',
            'hero.edit',

            'permission_read',
            'permission_create',
            'permission_update',

            'manage_plan',
            'manage_domain',
            'sms.history',
            'sms.credit',
            'sms_gateway',
            'usage',

            'merchant_create',
            'merchant_read',
            'use_all_merchant',
            'read_all_merchant',
            'merchant_update',
            'merchant_shop_read',
            'merchant_shop_create',
            'merchant_shop_update',
            'merchant_payment_account_read',
            'merchant_payment_account_update',
            'merchant_account_activity_read',
            'merchant_cod_charge_read',
            'merchant_charge_read',
            'merchant_payment_logs_read',
            'merchant_api_credentials_read',
            'merchant_api_credentials_update',
            'merchant_staff_read',
            'merchant_staff_create',
            'merchant_staff_update',
            'download_closing_report',
            'pickup_and_delivery_time_setting_update',
            'charge_setting',
            'packaging_charge_setting',
            'preference_setting',

            'deliveryman_create',
            'deliveryman_read',
            'read_all_delivery_man',
            'use_all_delivery_man',
            'deliveryman_update',
            'deliveryman_account_activity_read',
            'deliveryman_payment_logs_read',

            'parcel_create',
            'parcel_read',
            'parcel_update',

            'read_all_parcel',
            'parcel_pickup_assigned',
            'parcel_reschedule_pickup',
            'parcel_received_by_pickup_man',
            'parcel_received',
            'parcel_transfer_to_branch',
            'parcel_transfer_receive_to_branch',
            'parcel_delivery_assigned',
            'parcel_reschedule_delivery',
            'parcel_returned_to_warehouse',
            'parcel_return_assigned_to_merchant',
            'parcel_delivered',
            'parcel_backward',
            'parcel_returned_to_merchant',
            'parcel_cancel',
            'send_to_paperfly',

            'income_create',
            'income_read',
            'read_all_income',
            'income_update',

            'expense_create',
            'expense_read',
            'read_all_expense',
            'expense_update',

            'withdraw_read',
            'read_all_withdraw',
            'withdraw_create',
            'withdraw_update',
            'withdraw_process',
            'withdraw_reject',
            'add_to_bulk_withdraw',

            'sms_campaign_message_send',
            'custom_sms_send',

            'report_read',
            'transaction_history_read',
            'parcels_summary_read',
            'total_summary_read',
            'income_expense_report_read',
            'profit_summary_report_read',
            'merchant_summary_report_read',
            'dashboard_statistics_read',

            'account_read',
            'read_all_account',
            'account_create',
            'account_update',
            'account_statement',

            'fund_transfer_read',
            'read_all_fund_transfer',
            'fund_transfer_create',
            'fund_transfer_update',

            'branch_read',
            'branch_create',
            'branch_update',

            'third_party_read',
            'third_party_create',
            'third_party_update',

            'language_read',
            'language_create',
            'language_update',

            'payment_method_read',
            'payment_method_create',
            'payment_method_update',

            'country_read',
            'country_create',
            'country_update',

            'notice_read',
            'notice_create',
            'notice_update',

            'settings_read',
            'charge_setting_update',
            'pickup_and_delivery_time_setting_update',
            'preference_setting_update',
            'panel_setting',
            'preference',
            'payment_method',
            'general_setting',

            'bulk_withdraw_read',
            'read_all_bulk_withdraw',
            'bulk_withdraw_create',
            'bulk_withdraw_update',
            'bulk_withdraw_process',
            'download_payment_sheet',

            'news_and_event.index',
            'news_and_event.create',
            'news_and_event.edit',
            'about.index',
            'about.create',
            'about.edit',
            'service.index',
            'service.create',
            'service.edit',
            'feature.index',
            'feature.create',
            'feature.edit',
            'statistic.index',
            'statistic.create',
            'statistic.edit',

            'price.section',
            'contact.section',
            'website.themes',
            'website.menu',
            'section.title',
            'website.cta',
            'footer.content',
            'website_setting.seo',
            'website_setting.custom_js',
            'website_setting.custom_css',
            'website_setting.google_setup',
            'website_setting.fb_pixel',
            'partner_logo.index',
            'partner_logo.create',
            'partner_logo.edit',
            'testimonial.index',
            'testimonial.create',
            'testimonial.edit',
            'faq.index',
            'faq.create',
            'faq.edit',
            'pages.index',
            'pages.create',
            'pages.edit',
        ];
    }
};
